main: net.tfminecraft.DenarEconomy.DenarEconomy
api-version: '1.21.10'
name: DenarEconomy
version: ${project.version}
author: Drefvelin

depend: [MMOItems, MythicLib, TLibs]

commands:
  deco:
      usage: /<command>
      description: Economy Command
  pouch:
      usage: /<command>
      description: Pouch Command

permissions:
  denareconomy.reload:
    description: Reload DenarEconomy configs
    default: op